### ISSUE TITLE
Looks awesome, any plans to support PostgreSQL?

### ISSUE THREAD

**Issue by chmac** [mijia/modelq#2]
Firstly, modelq looks fantastic, exactly the right approach to reducing the leg work of working with an RDBMS in Go, thanks a lot. Were you inspired by [this](http://www.hydrogen18.com/blog/golang-orms-and-why-im-still-not-using-one.html) by any chance?

We're working with PostgreSQL. Any interest in supporting it? Any idea how much work would be involved in adding it if we were to try it ourselves?

**Comment by mijia** [comment]
@chmac Thank you very much for your interest. I did stumble upon the article you mentioned during the implementation, but I was actually inspired by Slick (https://github.com/slick/) since we are using it in web dev for our company.

I am now pretty occupied by the company dev stuff so very little time will spend on this project so far. I am quite interested in supporting different drivers for ModelQ, but now in the code, the sql statement part is very tightly coupled with the query part. So maybe costs some efforts to loose that couple with an extra driver layer for this. Maybe it will be easy to do, but I have no idea for now, :) I will definitely think about this.

Any fork or pull request would be appreciated, :)

**Comment by mijia** [comment]
@chmac Hi, I have implemented the PostgresQL into ModelQ, please help to check it out if you got some time, :)
So far, I have 2 problems since I am not quite familiar with PostgresQL
1. lib/pq doesn't support GetLastInsertID, so I am still struggling with the interface design for the "INSERT .... RETURNING ...." structure, any suggestions?
2. I found it seems lib/pq has some problems supporting time.Time scan so it will fail if there is a column has the type timestamp, I think I might be using the api incorrectly.

Any feedbacks would be appreciated.
Thank you very much
